name: PHP Linting (Pint)
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "dependabot/npm_and_yarn/*"
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel
